version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000" # חשיפת השרת
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app # כדי לאפשר שינויים בזמן אמת בקוד
    command: ["npm", "run", "start"] # או הפקודה המתאימה לשרת שלך

  client:
    build:
      context: ./client
    ports:
      - "3000:80" # חשיפת הקליינט
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000
    volumes:
      - ./client:/app # כדי לאפשר שינויים בזמן אמת בקוד
    command: ["npx", "serve", "-s", "build"] # או הפקודה המתאימה לקליינט שלך

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # חשיפת MongoDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
