version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "6000:6000" # חשיפת השרת
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app_network
    command: ["npm", "run", "start"]

  client:
    build:
      context: ./client
    ports:
      - "3000:80" # חשיפת הקליינט
    environment:
      - REACT_APP_SERVER_URL=http://server:6000
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # חשיפת MongoDB
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo-data:
