version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000" # חשיפת השרת
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app # כדי לאפשר שינויים בזמן אמת בקוד
    command: ["npm", "run", "start"] # הפקודה המתאימה לשרת שלך

  client:
    build:
      context: ./client
    ports:
      - "3000:80" # חשיפת הקליינט
    environment:
      - REACT_APP_SERVER_URL=http://server:5000
    volumes:
      - ./client:/app # כדי לאפשר שינויים בזמן אמת בקוד

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # חשיפת MongoDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
