version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "7000:7000" # חשיפת ה-API למחשב המארח
    volumes:
      - .:/server
      - /server/node_modules # מניעת בעיות עם node_modules
    depends_on:
      - mongo
    networks:
      - app_network

  client:
    build:
      context: ./client
    ports:
      - "3000:80" # חשיפת הקליינט
    environment:
      - REACT_APP_SERVER_URL=http://localhost:7000
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # חשיפת MongoDB
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongo-data:
